### ISSUE TITLE
logo ordering and rendering

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/osdforum.org#11]
@autumnfound  - logos should be alphabetical and the ~ same size relative to each other.

**Comment by autumnfound** [comment]
@rickoco I can do the ordering bit, that's easy. The rendering thing however, due to the logos having different aspect ratios (Core V and CMC Microsystems being the big offenders) they will never look perfect. They already have a fixed width, and each of the logos take up the same amount of horizontal real estate.

**Comment by autumnfound** [comment]
This is live. If you'd like more changes to the logos, please open a new issue
