### ISSUE TITLE
Agenda Update

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/osdforum.org#48]
@chrisguindon @autumnfound - guys we've tweaked the order of the agenda somewhat and there was also some typos / spacing / line break issues on what was posted to the site.

Updated content is here...
https://docs.google.com/spreadsheets/d/18yqcTMmf0BnNW9D3tiyGNn6UcIYHMR9Y90s1s0VThTY/edit?usp=sharing

**Comment by autumnfound** [comment]
I fixed the typo in one of the names (Afredo Herrera), switched the 11:15 and 11:45 sessions, but otherwise couldn't find any differences.
Also, for the spacing, do you mean the double session for Jerry Zeng? Because of how the agenda is built, the double session currently isn't able to be printed together. Is there exact time slots for those sessions?

**Comment by autumnfound** [comment]
@rickoco any word on this?

**Comment by rickoco** [comment]
sorry @autumnfound - I was away on travel.  For name typo it should be Alfredo with an 'l' after the A and not Alfredo.

Spacing issue I was referring to a line break in Hugh Pollitt-Smith's name at the bottom of the agenda for the last item (panel discussion) of the day before the wrap up.

**Comment by autumnfound** [comment]
That's just how it ended up being printed in that style. How does this look? The names don't break but the companies do at times:
![image](https://user-images.githubusercontent.com/23018241/64261468-93e64b80-cefa-11e9-8dda-fc3279ededce.png)

**Comment by chrisguindon** [comment]
Thanks @autumnfound
