### ISSUE TITLE
OSDForum 2020 Agenda

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/osdforum.org#73]
Please post the following agenda on the osdforum.org landing page https://docs.google.com/spreadsheets/d/1zQkedb07pFQBP6is7lfTdKHNfuk6AUfy8-aaLlniD40/edit?usp=sharing

Follow the same format as was used for the 2019 agenda https://www.osdforum.org/2019/

**Comment by autumnfound** [comment]
@rickoco due to some changes in how we do events, we can't immediately give 100% the same look and feel. This comes with some new features though, like session abstracts. The one difference in new vs old that is noticeable is the handling of Hands-on sessions. Before we had bold text which isn't possible in the new agenda. You can look at https://events.eclipse.org/2020/open-source-ai-workshop/ and https://jakartaone.org/2020/cn4j/ for examples of how we use agendas now. Would you want a legend denoting a hands on session, or just text in the session name?

**Comment by autumnfound** [comment]
Addditionally, a preview of how the 2020 agenda currently looks can be seen at https://5f205c720f54410007c5340d--eclipsefdn-osdforum.netlify.app/.

**Comment by rickoco** [comment]
@autumnfound the format for both the AI and jakarta events look great - having session abstracts is a definite bonus!!  I'm good with either one - you decide with one you'd like to use for OSDForum 2020 (I also like the speaker headshots which helps promote the event and encourage registration).   Yes, please include the legend so we can highlight 'hands on' sessions as these are an important draw.  We'll send through abstract and speaker, titles / headshots later, so for this week the agenda as is would be great!  Post event we'll want to update the agenda with links to session videos and slides.

**Comment by autumnfound** [comment]
@rickoco if you open the preview and refresh you should see a legend with a few quick colours selected! Let me know if that works for you or if you want the labels updated. The labels can be configured by agenda instance so it's pretty flexible!

**Comment by rickoco** [comment]
> @rickoco if you open the preview and refresh you should see a legend with a few quick colours selected! Let me know if that works for you or if you want the labels updated. The labels can be configured by agenda instance so it's pretty flexible!

Thx @autumnfound - colours are fine, but can we swap red for the hands-on and beige for the other sessions pls?  We'd like the hands-on sessions to stand out :-)

**Comment by autumnfound** [comment]
Done, and live!
